package:
  name: PyNaCl
  version: 1.3.0
source:
  sha256: 0c6100edd16fefd1557da078c7a31e7b7d7a52ce39fdca2bec29d4f7b6e7600c
  url: https://files.pythonhosted.org/packages/61/ab/2ac6dea8489fa713e2b4c6c5b549cc962dd4a842b5998d9e80cf8440b7cd/PyNaCl-1.3.0.tar.gz
build:
  skip_host: False
  ldflags: -L/usr/local/lib
test:
  imports:
  - PyNaCl
