package:
  name: cryptography
  version: 2.6.1
source:
  sha256: 26c821cbeb683facb966045e2064303029d572a87ee69ca5a1bf54bf55f93ca6
  url: https://files.pythonhosted.org/packages/07/ca/bc827c5e55918ad223d59d299fff92f3563476c3b00d0a9157d9c0217449/cryptography-2.6.1.tar.gz
build:
  skip_host: False
  cflags: -I/opt/openssl/include/
  ldflags: -L/opt/openssl/
test:
  imports:
  - cryptography
